### ISSUE TITLE
Версии зависимостей

### ISSUE THREAD

**Issue by kelvionald** [SashaOcheev/AspNetMvcLesson#1]
Добрый день.

Делаю проект по вашему гайду. И столкнулся с проблемами и ошибками. Я думаю они разрешатся если вы укажете версию ASP.NET Core и версии зависимостей:
Microsoft.AspNetCore.StaticFiles
AspNet.AspNetCore.Mvc.Core

С уважением, Сергей.

**Comment by SashaOcheev** [comment]
Добрый день.
Все уроки (5 штук) лежат каждый в своей ветке. Они последовательно развивают проект. Вы можете открыть любую из них и найти там AspNetMvcLesson/Shop/Shop/Shop.csproj . Там указаны все завмсимости и все версии
